DRONE_COMMANDS = {
    # "arm": [0, 1, 400, 0, 1, 0, 0, 0, 0, 0, 0],
    # "disarm": [0, 1, 400, 0, 0, 0, 0, 0, 0, 0, 0],
    "arm": {
        "target_system": 0,
        "target_component": 1,
        "command": 400,
        "confirmation": 0,
        "param1": 1,
        "param2": 0,
        "param3": 0,
        "param4": 0,
        "param5": 0,
        "param6": 0,
        "param7": 0,
    },
    "disarm": {
        "target_system": 0,
        "target_component": 1,
        "command": 400,
        "confirmation": 0,
        "param1": 0,
        "param2": 0,
        "param3": 0,
        "param4": 0,
        "param5": 0,
        "param6": 0,
        "param7": 0,
    },
}
